FROM docker.io/rockylinux:9
LABEL maintainer "Mikko Strahlendorff <mikko.strahlendorff@fmi.fi>"
LABEL license    "MIT License Copyright (c) 2025 FMI Open Development"

ENV USER_NAME="smartmet" \
    GOOGLE_FONTS="Montserrat NotoSans OpenSans Roboto" 

RUN dnf -y install https://download.fmi.fi/smartmet-open/rhel/9/x86_64/smartmet-open-release-latest-9.noarch.rpm && \
    dnf -y install yum-utils && \
    dnf config-manager --set-enabled crb && \
    dnf -y install epel-release && \
    dnf config-manager --setopt="epel.exclude=librsvg2*" --save && \
    dnf config-manager --setopt="baseos.exclude=librsvg2*" --save && \
    dnf config-manager --setopt="epel.exclude=eccodes*" --save && \
    dnf config-manager --set-disabled epel-source && \ 
    dnf -y module disable postgresql:15 && \
    dnf -y install https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm && \
    dnf config-manager --disable "pgdg*" && \
    sed -i -e 's/-source\]$/-__source]/' /etc/yum.repos.d/*.repo && \
    dnf -y update && \
    dnf -y install "glibc-langpack-*" postgresql-server && \
    ln -sf /usr/share/zoneinfo/Europe/Helsinki /etc/localtime && \
    dnf -y install --setopt=install_weak_deps=False \
    smartmet-plugin-admin \
    smartmet-plugin-autocomplete \
    smartmet-plugin-backend \
    smartmet-plugin-download \
    smartmet-plugin-edr \
    smartmet-plugin-timeseries \
    smartmet-plugin-wms \
    smartmet-engine-grid \
    smartmet-plugin-grid-admin \
    smartmet-plugin-grid-gui \
    smartmet-tools-grid \
    glibc-langpack-en && \
    dnf -y reinstall --setopt=override_install_langs='' --setopt=tsflags='' glibc-common eccodes && \
    dnf clean all 

# Install Google Fonts
RUN \
    for FONT in $GOOGLE_FONTS; \
    do \
        mkdir -p /usr/share/fonts/truetype/${FONT} && \
        curl -s -S --output-dir /usr/share/fonts/truetype/${FONT}  "https://github.com/google/fonts/raw/main/ofl/${FONT,,}/${FONT}%5Bwdth,wght%5D.ttf" && \
        curl -s -S --output-dir /usr/share/fonts/truetype/${FONT}  "https://github.com/google/fonts/raw/main/ofl/${FONT,,}/${FONT}-italic%5Bwdth,wght%5D.ttf" ; \
    done

HEALTHCHECK --interval=30s --timeout=10s \
  CMD curl -f http://localhost:8080/admin?what=qengine || exit 1

# Expose SmartMet Server's default port
EXPOSE 8080

RUN groupadd -r -g 1000 smartmet
RUN useradd -r -u 1001 -g smartmet smartmet

RUN mkdir -p /srv/data/ 
#{meps,hirlam,gfs,meteor,nam,icon,gem,gens-avg,gens-ctrl,hbm,wam,aws}/{surface,pressure} \
#             /smartmet/share/wms

RUN install -m 775 -g 0 -d /var/smartmet
RUN chown -R smartmet /srv/data /var/log/smartmet /var/smartmet
RUN touch /var/log/smartmet/info-access-log
RUN chown smartmet /var/log/smartmet/info-access-log
COPY scripts /home/smartmet/scripts 
RUN chown -R smartmet /home/smartmet/*
RUN chmod -R g=u /var/smartmet /etc/passwd /var/log/smartmet

COPY docker-entrypoint.sh /

### Containers should NOT run as root as a good practice
USER smartmet

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["smartmetd"]